In [1]:
import pandas as pd
import numpy as np

In [18]:
weather = ['sunny', 'overcast', 'rainy', 'sunny', 'sunny', 'overcast', 'rainy', 'rainy', 'sunny', 'rainy', 'sunny', 'overcast', 'overcast', 'rainy']
play = ['no', 'yes', 'yes', 'yes', 'yes', 'yes', 'no', 'no', 'yes', 'yes', 'no', 'yes', 'yes', 'no']

df = pd.DataFrame(data={'weather':weather, 'play':play}, columns=['weather', 'play'])
df.head()

weather play
0     sunny   no
1  overcast  yes
2     rainy  yes
3     sunny  yes
4     sunny  yes

In [19]:
df['play'] = df['play'].apply(lambda x: 1 if x=='yes' else 0)
df = pd.concat([df, pd.get_dummies(df['weather'])], axis=1)
df.drop(['weather'], axis=1, inplace=True)
df.head()

play  overcast  rainy  sunny
0     0         0      0      1
1     1         1      0      0
2     1         0      1      0
3     1         0      0      1
4     1         0      0      1

In [20]:
from sklearn.naive_bayes import GaussianNB

In [33]:
model = GaussianNB()
gaussian_model = model.fit(df[['overcast', 'rainy', 'sunny']], df['play'])
gaussian_model.sigma_

array([[2.29591837e-10, 2.40000000e-01, 2.40000000e-01],
       [2.46913580e-01, 1.72839506e-01, 2.22222222e-01]])

In [27]:
gaussian_model.predict([[0, 1, 0]])

array([0], dtype=int64)

In [34]:
gaussian_model.predict([[1, 0, 0]])

array([1], dtype=int64)